[RM Ch08] Extreme-edge devices reference
anuket-project/anuket-specifications pull request #3255
Opened 2022-11-18 02:51 UTC by joaoarodrigues

2022-11-21 03:06 UTC, walterkozlowski approved these changes

2022-11-23 20:42 UTC, petorre approved these changes

2022-11-23 21:35 UTC, walterkozlowski commented
At RM Meeting pn 23 November 2022: discussion that we do not cover orchestration in RM; discussion to be continued post Nile

2022-11-24 00:32 UTC, joaoarodrigues commented
The main point here was to consider extreme-edge devices, its not about the orchestration

2022-11-24 07:45 UTC, CsatariGergely requested changes

2022-11-24 07:45 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter08.rst
> +Finally, there is a need to integrate, and to consider extreme-edge devices which can be part of the ecosystem, and offer programability and processing capabilities. Ultimately, can be considered for
Please wrap lines to 120 chars.

2022-11-24 10:46 UTC, joaoarodrigues commented on doc/ref_model/chapters/chapter08.rst
> +Finally, there is a need to integrate, and to consider extreme-edge devices which can be part of the ecosystem, and offer programability and processing capabilities. Ultimately, can be considered for
```suggestion
Finally, there is a need to integrate, and to consider extreme-edge devices which can be part of the ecosystem,
 and offer programability and processing capabilities. Ultimately, can be considered for the end-to-end 
 orchestration, and can be used to comply with extreme requirements for some of the use cases. 
```

2022-11-24 11:35 UTC, CsatariGergely approved these changes

2022-11-29 10:29 UTC, rgstori approved these changes

2022-12-07 21:48 UTC, jbhartley commented
Suggest:

1. We include content into prior paragraph
2. Clarify wording

Suggest:

At the edge, the infrastructure may further include ruggedised hardware for harsh environments and hardware with
different form factors. With the evolution of IoT and ubiquitous connectivety (inclusive of personal devices) to consider extreme-edge devices as part of the ecosystem.  This will require need to integrate with and offer programability and processing capabilities for these devices. The end-to-end orchestration will need to support the extreme edge use cases.

2022-12-09 00:55 UTC, pgoyal01 commented on doc/ref_model/chapters/chapter08.rst
> +Finally, there is a need to integrate, and to consider extreme-edge devices which can be part of the ecosystem,
As discussed in the RM meeting of 2022-12-07, starting the sentence with "Finally" doesn't follow the previous sentences. If this suggestion is accepted, then lines 663 and 664 should be deleted. Orchestration is not the topic of this section and so is being removed.

If orchestration must be mentioned, then it should be a separate paragraph that applies to the content of this section.
```suggestion
Additionally, the extreme edge may consist of programmable devices as part of the
Telco Edge Cloud ecosystem for use in meeting some extremely low latency requirements,
```

2022-12-15 18:32 UTC, steelescotr commented
@walterkozlowski - would you be able to finalize this PR so we can be sure it's in the Nile Release?

2022-12-16 11:16 UTC, joaoarodrigues commented
> Suggest:
> 
> 1. We include content into prior paragraph
> 2. Clarify wording
> 
> Suggest:
> 
> At the edge, the infrastructure may further include ruggedised hardware for harsh environments and hardware with different form factors. With the evolution of IoT and ubiquitous connectivety (inclusive of personal devices) to consider extreme-edge devices as part of the ecosystem. This will require need to integrate with and offer programability and processing capabilities for these devices. The end-to-end orchestration will need to support the extreme edge use cases.

@jbhartley Thank you for the proposal. I've updated it, and corrected a couple of typo's 😊

2022-12-16 11:17 UTC, joaoarodrigues commented
> @walterkozlowski - would you be able to finalize this PR so we can be sure it's in the Nile Release?

2023-01-11 23:02 UTC, merged