[RI2] Switch to Piccolo Sphinx theme
anuket-project/anuket-specifications pull request #3308
Opened 2023-01-29 03:43 UTC by xudan16

2023-01-30 16:41 UTC, steelescotr approved these changes

2023-02-05 13:36 UTC, CsatariGergely requested changes
Thanks for the proposal. I've added some fixes to https://github.com/xudan16/anuket-specifications/pull/1

2023-02-06 01:49 UTC, xudan16 commented
@CsatariGergely Thanks for the updates. Have merged that 2 commits.

2023-02-06 06:26 UTC, CsatariGergely approved these changes

2023-02-06 08:13 UTC, gkunz approved these changes

2023-02-07 01:33 UTC, merged