[Ra2 ch3, ch4] language alterations
anuket-project/anuket-specifications pull request #3309
Opened 2023-02-02 09:21 UTC by mpgreaves

2023-02-08 16:38 UTC, steelescotr approved these changes

2023-02-09 09:13 UTC, petorre approved these changes

2023-02-24 14:49 UTC, rgstori approved these changes

2023-02-27 10:18 UTC, rgstori approved these changes
approved, just a couple spelling fixes

2023-02-27 10:18 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter03.rst
> +   provides a centralized point by which the networking solution is managed using a centralized management API.
british spelling
```suggestion
   provides a centralised point by which the networking solution is managed using a centralised management API.
```

2023-02-27 10:36 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter07.rst
> +:ref:`chapters/chapter03:management of memory and huge pages resources`.
trailing whitespace here

2023-02-27 10:36 UTC, rgstori requested changes
trailing whitespace

2023-03-02 09:34 UTC, CsatariGergely commented
> trailing whitespace

@rgstori this is fixed now and ready to be merged.

2023-03-13 10:44 UTC, rgstori approved these changes

2023-03-13 10:44 UTC, merged