[RI2 Ch02] Update RI2 requirements based on RA2 Nile
anuket-project/anuket-specifications pull request #3340
Opened 2023-04-11 02:31 UTC by zhuguanyu5

2023-04-11 06:43 UTC, zhuguanyu5 commented on doc/common/references.rst
> +       <https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53Ar5.pdf>`__.
the original URL is invalid.

2023-04-11 06:43 UTC, zhuguanyu5 commented on doc/ref_impl/cntt-ri2/chapters/chapter02.rst
> +      - ``ra2.ntw.016``
aline to RA2 Nile release

2023-06-07 14:30 UTC, CsatariGergely requested changes

2023-06-07 14:30 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri2/chapters/chapter01.rst
> +To facilitate the rapit deployment of the RI and avoid redundant effort across communities, the RI community
```suggestion
To facilitate the rapid deployment of the RI and avoid redundant effort across communities, the RI community
```

2023-07-03 09:22 UTC, closed without merging