[ra2_ch6]: language-corrections
anuket-project/anuket-specifications pull request #3384
Opened 2023-07-20 08:57 UTC by mpgreaves

2023-07-20 09:24 UTC, petorre approved these changes

2023-07-24 09:05 UTC, CsatariGergely commented
Build is broken due to #3385

2023-07-24 09:08 UTC, rgstori requested changes
Hi @mpgreaves , thanks for this, although I think that `Special Interest Group` should be capitalised (see [here](https://github.com/kubernetes/community/blob/master/sig-list.md))

2023-07-27 08:32 UTC, mpgreaves commented
Fixed in [47deb9e](https://github.com/anuket-project/anuket-specifications/pull/3384/commits/47deb9e578f7b72dfda076a898710c0c0e1c661a)

2023-07-31 09:28 UTC, rgstori approved these changes

2023-07-31 09:28 UTC, merged