[RM Ch03] Add redfish as Hardware Infrastructure Manager option
anuket-project/anuket-specifications pull request #3413
Opened 2023-09-19 17:06 UTC by Bharath-KKB

Closed the old PR that included ODIM. This new PR proposes redfish as an option for the Hardware Infrastructure Manager in chapter 3 of the reference model.

2023-10-01 08:43 UTC, collivier requested changes
Because of RTD forcing the use of .readthedocs.yaml, we don't have another choice than splitting the git repository per stream. This PR must be applied on next RM's git repository and not here.

Everything is already ready on my own repositories but sadly I don't have the rights needed on anuket-project organization. **Please give me them to complete the migration.**

Be free to ask for any  detail about the migration during a Weekly Technical meeting.

2023-10-03 08:16 UTC, walterkozlowski approved these changes

2023-10-04 12:44 UTC, joaoarodrigues reviewed
TEST

2023-10-04 12:53 UTC, petorre commented on doc/ref_model/chapters/chapter03.rst
> +This section proposes a Redfish based hardware infrastructure manager for the Anuket project. ODIM software architecture is an example of an open source project implementing Redfish standard.
```suggestion
This section proposes a Redfish based hardware infrastructure manager for the Anuket project. Open Distributed Infrastructure Management (ODIM) is an open source software platform that delivers means of distributed physical infrastructure lifecycle management based on the industry standard DMTF Redfish API and Model specification.
```

2023-10-04 12:53 UTC, petorre commented on doc/ref_model/chapters/chapter03.rst
> +Chapter 9 (:ref:`chapters/chapter09:Configuration and Lifecycle Management`) of this reference model specifies redfish standard for managing Infrastructure Hardware. The GSMA's "Cloud Infrastructure
```suggestion
Chapter 9 (:ref:`chapters/chapter09:Configuration and Lifecycle Management`) of this reference model specifies Redfish standard for managing Infrastructure Hardware. The GSMA's "Cloud Infrastructure Reference Model (NG.126)" also specifies Redfish as the standard interface that should be 
```

2023-10-04 12:54 UTC, petorre commented on doc/ref_model/chapters/chapter03.rst
> +How redfish fits into the ETSI NFV Networking Reference Model
```suggestion
How Redfish fits into the ETSI NFV Networking Reference Model
```

2023-10-18 12:36 UTC, walterkozlowski commented
@collivier, is there a way we can merge this, and discuss the repo issues somewhere else?

2023-11-08 09:46 UTC, joaoarodrigues approved these changes

2023-12-06 16:12 UTC, collivier commented on doc/ref_model/chapters/chapter03.rst
> +-	**Additional Management Functions**: The Redfish schema has models for access management and identity management. Redfish has published work-in-progress extension for support policy management and
this link isn't publicly readable (access - denied).
Would you mind replacing it or worse making an linkcheck exception in setup.py

2023-12-06 16:14 UTC, collivier commented
@walterkozlowski be free to merge it if urgent but I would rather suggest to fix the link which is access denied.
No worries I will manage the cherry-picking in the new repos.

2023-12-07 09:58 UTC, walterkozlowski approved these changes

2023-12-07 12:26 UTC, collivier approved these changes

2023-12-07 12:27 UTC, collivier commented
@walterkozlowski I merge it but the current build is broken because of wrong link in chapter 7 (out this scope)
https://www.cyber.gov.au/acsc/view-all-content/ism/ -> https://www.cyber.gov.au/resources-business-and-government/essential-cyber-security/ism ?

2023-12-07 12:28 UTC, merged